# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.csv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: units.csv

# the sequencing adapter
adapter: TGGAATTCTCGGGTGCCAAGG

ref:
  # the STAR index
  index: "~/data/star-2.4/"
  # gtf file with transcripts
  # mmu.gtf in version v21
  # mir_annotation: "~/data/mmu21.gff3"
  # complete_annotation: ~/data/gencode.vM20.annotation.gff3

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

# TODO add formula?

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    all-mirnas:
      positive:
        - typewt
      negative:
        - typedicer
    canonical-mirnas-confident-samples:
      positive:
        - typewt
      negative:
        - typedrosha
        - typedgcr8
    noncanonical-mirnas-confident-samples:
      positive:
        - typedrosha
      negative:
        - typedicer
    canonical-mirnas-many-samples:
      positive:
        - typewt
      negative:
        - typedrosha
        - typedgcr8
        - typedicer
        - typeago12
    noncanonical-mirnas-many-samples:
      positive:
        - typewt
        - typedrosha
        - typedgcr8
      negative:
        - typedicer
        - typeago12
    canonical-mirnas-weighted-samples:
      positive:
        - typewt
      negative:
        - typedrosha
        - typedgcr8
        - typedicer
        - typeago12
      list_values: [1, -0.4, -0.3, -0.2, -0.1]  # dgcr8 drosha are most relevant, then dicer and last ago12
    noncanonical-mirnas-weighted-samples:
      positive:
        - typewt
        - typedrosha
        - typedgcr8
      negative:
        - typedicer
        - typeago12
      list_values: [0.1, 0.45, 0.45, -0.7, -0.3]  # WT shouldn't play an important role as it contains both canonical and non-canonical

params:
  star: "--outFilterMismatchNoverLmax 0.05"  # leads to 0 mismatch for <20b and 1 masmatich 20-39bp
  feature_counts: "-M -f -O -t exon -g gene_id" # "-t miRNA -g Name"
  cutadapt-se: "-m 17 -M 30"
  cutadapt-pe: ""
